"""
Profile specific manually curated highlights.
"""

highlights = {
    1: "reflects the highest proportion of the population (25% of households). This is also group with the highest percentage of households where all occupants are aged 65+ at 40%, and a high percentage of households with no working adults (either due to retirement or other). Across other characteristics, households in profile 1 are in line with the overall average.",
    2: "has the lowest annual electricity and gas consumption, and has the greatest proportion of households in social housing. This profile has the greatest proportion of single occupancy households, and the lowest proportion of households with children. At least 38% of properties in this profile have EPC rating of C or above, the highest of all profiles.",
    3: "has second lowest annual electricity and gas usage, and the highest proportion of households where all adults in the household either work or study. 35% of properties in this profile have EPC rating of C or above, the second highest of all profiles.",
    4: "has the second highest annual gas consumption. 36% are households where all occupants are aged 65+, and 50% of households live in detached properties. This profile contains a higher than average proportion of households living in properties built before 1930.",
    5: "consists of a higher than average proportion of households with children (at least 38%), and over 50% of households with 3 or more occupants. 6% have air conditioning units. 27% have smart heating controls.",
    6: "this profile has a higher than average percentage of households in social rentals (at least 12% of households) and the second highest portion of households (48%) in the most deprived areas. This profile is mostly in line with the average across most characteristics.",
    7: "Most households in profile 7 don’t consume gas and 34% of properties have an EPC rating of C or above. While most electricity consumption profiles show a morning increase and an evening peak, profile 7 exhibits particularly distinct trimodal peaks throughout the day. This profile has the highest proportion of private renters (at least 30%) and highest proportion of households living in flats (at leat 40%). At least 11% have solar panels, 8% have battery storage and 6% have heat pumps. 27% are on a time-of-use tariff (third highest value).",
    8: "has the highest annual gas consumption of all profiles and the lowest percentage of properties with EPC rating of C or above (at least 10% of properties). This profile has the highest percentage of high-income households (at least 20% earn more than £90K per year). They tend to be larger households (over 50% have three or more occupants). This profile has the highest proportion of houses in Greater London, 23%. Over 40% of households live in properties built before 1930 and over 50% in detached properties. 32% have smart heating controls.",
    9: "is the second smallest profile (3% of households) and has the second highest electricity consumption on average. This is the group of 'overnight electricity consumers': this group's consumption peaks overnight, likely driven by electric vehicle ownership (over 60% of households own an EV) and battery storage (at least 8%). There are affluent (at least 15% earn £90K or more), high-tech households in this profile, with many owning solar panels (over 21%), air conditioning (over 10%) and smart heating controls (highest proportion of 44%). 35% of households are on a time-of-use tariff (second highest of all profiles). They tend to be larger families (over 64% have three or more occupants) residing in detached properties (over 50%).",
    10: "reflects the smallest proportion of the population (2% of households) and has the highest electricity consumption of all profiles on average with most households being off-gas. While most electricity consumption profiles show a morning increase and an evening peak, profiles 10 exhibits particularly distinct trimodal peaks throughout the day. A higher than average proportion of households (at least 12%) earn more than £90K per year and over 50% live in detached houses. There are affluent, high-tech households in this profile: 32% have a heat pump, 22% have electric vehicles, 22% have solar panels and 10% have air conditioning. 38% of households are on a time-of-use tariff (highest of all profiles).",
}
